//! Raw FFI bindings to the Agora NG/RTSA flat C API, generated by bindgen
//! in build.rs from the SDK headers staged by CMake.
#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case, dead_code)]

include!(concat!(env!("OUT_DIR"), "/agora_sys.rs"));
