//! Encoded + raw local video publishers. Each owns the SDK sender +
//! track handles; Drop unpublishes + destroys both.
//!
//! The encoded path routes through the C++ shim (`cpp/agora_shim.cpp`)
//! because the SDK's flat-C `agora_video_encoded_image_sender_send` is
//! broken — see README §Known Issues. The raw path still uses the flat
//! C API directly.

use std::os::raw::c_void;
use std::ptr;

use super::error::{check, AgoraError};
use super::shim;
use super::sys;

// VIDEO_CODEC_TYPE / VIDEO_BUFFER_TYPE / VIDEO_PIXEL_FORMAT / VIDEO_FRAME_TYPE
// values from the SDK's AgoraBase.h (C++ header — not generated by bindgen).
const VIDEO_CODEC_H264: i32 = 2;
const VIDEO_BUFFER_RAW_DATA: i32 = 1;
const VIDEO_PIXEL_I420: i32 = 1;

pub struct EncodedVideoPublisher {
    /// Opaque pointer returned by `cppshim_video_encoded_create`. Owns
    /// the C++ refptr<IVideoEncodedImageSender> + refptr<ILocalVideoTrack>.
    shim: *mut shim::cppshim_video_pub,
    /// Flat-C connection handle (used for publish/unpublish via the shim).
    conn: *mut c_void,
    width: i32,
    height: i32,
    fps_num: u32,
    fps_den: u32,
}

// SAFETY: the shim pointer is opaque and we never alias it across threads
// without external synchronisation; the pump task owns the publisher
// exclusively.
unsafe impl Send for EncodedVideoPublisher {}

pub struct RawVideoPublisher {
    sender: *mut c_void,
    track: *mut c_void,
    conn: *mut c_void,
    width: i32,
    height: i32,
}

unsafe impl Send for RawVideoPublisher {}

pub(super) fn create_encoded(
    svc: *mut c_void,
    conn: *mut c_void,
    factory: *mut c_void,
) -> Result<EncodedVideoPublisher, AgoraError> {
    let p = unsafe { shim::cppshim_video_encoded_create(svc, factory, VIDEO_CODEC_H264) };
    if p.is_null() {
        return Err(AgoraError::null("cppshim_video_encoded_create"));
    }
    Ok(EncodedVideoPublisher {
        shim: p,
        conn,
        width: 0,
        height: 0,
        fps_num: 30,
        fps_den: 1,
    })
}

pub(super) fn create_raw(
    svc: *mut c_void,
    conn: *mut c_void,
    factory: *mut c_void,
) -> Result<RawVideoPublisher, AgoraError> {
    let sender = unsafe {
        sys::agora_media_node_factory_create_video_frame_sender(factory)
    };
    if sender.is_null() {
        return Err(AgoraError::null(
            "agora_media_node_factory_create_video_frame_sender",
        ));
    }
    let track = unsafe { sys::agora_service_create_custom_video_track_frame(svc, sender) };
    if track.is_null() {
        unsafe {
            sys::agora_video_frame_sender_destroy(sender);
        }
        return Err(AgoraError::null(
            "agora_service_create_custom_video_track_frame",
        ));
    }
    unsafe {
        sys::agora_local_video_track_set_enabled(track, 1);
    }
    Ok(RawVideoPublisher {
        sender,
        track,
        conn,
        width: 0,
        height: 0,
    })
}

impl EncodedVideoPublisher {
    /// Set the picture dimensions and frame-rate ratio. Call once after
    /// the first H.264 AU has been seen and the source's width/height/fps
    /// are known (or pass values from `MediaInfo`).
    pub fn set_metadata(&mut self, width: u32, height: u32, fps_num: u32, fps_den: u32) {
        self.width = width as i32;
        self.height = height as i32;
        self.fps_num = fps_num;
        self.fps_den = fps_den.max(1);
    }

    /// Push one Annex-B-framed H.264 access-unit. `_capture_time_ms` is
    /// accepted for symmetry with the raw path but not forwarded — the
    /// C++ shim derives timing from `frames_per_second`.
    pub fn push_h264(
        &self,
        au: &[u8],
        is_keyframe: bool,
        _capture_time_ms: i64,
    ) -> Result<(), AgoraError> {
        let fps = (self.fps_num as i32) / (self.fps_den as i32).max(1);
        let rc = unsafe {
            shim::cppshim_video_encoded_send(
                self.shim,
                au.as_ptr(),
                au.len() as u32,
                if is_keyframe { 1 } else { 0 },
                fps.max(1),
            )
        };
        check(rc, "cppshim_video_encoded_send")
    }

    pub fn publish(&self) -> Result<(), AgoraError> {
        let rc = unsafe { shim::cppshim_video_encoded_publish(self.shim, self.conn) };
        check(rc, "cppshim_video_encoded_publish")
    }

    pub fn unpublish(&self) -> Result<(), AgoraError> {
        let rc = unsafe { shim::cppshim_video_encoded_unpublish(self.shim, self.conn) };
        check(rc, "cppshim_video_encoded_unpublish")
    }
}

impl Drop for EncodedVideoPublisher {
    fn drop(&mut self) {
        if !self.shim.is_null() {
            unsafe {
                let _ = shim::cppshim_video_encoded_unpublish(self.shim, self.conn);
                shim::cppshim_video_encoded_destroy(self.shim);
            }
            self.shim = ptr::null_mut();
        }
    }
}

impl RawVideoPublisher {
    pub fn set_dimensions(&mut self, width: u32, height: u32) {
        self.width = width as i32;
        self.height = height as i32;
    }

    /// Push one yuv420p frame. `data` must be exactly width*height*3/2 bytes
    /// of planar Y+U+V; caller sizes it via `parse::yuv::frame_bytes`.
    pub fn push_yuv420p(&self, data: &[u8], pts_ms: i64) -> Result<(), AgoraError> {
        let mut frame: sys::external_video_frame = unsafe { std::mem::zeroed() };
        frame.type_ = VIDEO_BUFFER_RAW_DATA;
        frame.format = VIDEO_PIXEL_I420;
        frame.buffer = data.as_ptr() as *mut _;
        frame.stride = self.width;
        frame.height = self.height;
        frame.rotation = 0;
        frame.timestamp = pts_ms;
        let rc = unsafe { sys::agora_video_frame_sender_send(self.sender, &frame) };
        check(rc, "agora_video_frame_sender_send")
    }

    pub fn publish(&self) -> Result<(), AgoraError> {
        let local = unsafe { sys::agora_rtc_conn_get_local_user(self.conn) };
        let rc = unsafe { sys::agora_local_user_publish_video(local, self.track) };
        check(rc, "agora_local_user_publish_video")
    }

    pub fn unpublish(&self) -> Result<(), AgoraError> {
        let local = unsafe { sys::agora_rtc_conn_get_local_user(self.conn) };
        let rc = unsafe { sys::agora_local_user_unpublish_video(local, self.track) };
        check(rc, "agora_local_user_unpublish_video")
    }
}

impl Drop for RawVideoPublisher {
    fn drop(&mut self) {
        unsafe {
            let local = sys::agora_rtc_conn_get_local_user(self.conn);
            let _ = sys::agora_local_user_unpublish_video(local, self.track);
            sys::agora_local_video_track_destroy(self.track);
            sys::agora_video_frame_sender_destroy(self.sender);
        }
    }
}
