//! Encoded + raw local video publishers. Each owns the SDK sender +
//! track handles; Drop unpublishes + destroys both.

use std::os::raw::c_void;

use super::error::{check, AgoraError};
use super::sys;

// VIDEO_CODEC_TYPE / VIDEO_BUFFER_TYPE / VIDEO_PIXEL_FORMAT / VIDEO_FRAME_TYPE
// values from the SDK's AgoraBase.h (C++ header — not generated by bindgen).
const VIDEO_CODEC_H264: i32 = 2;
const VIDEO_BUFFER_RAW_DATA: i32 = 1;
const VIDEO_PIXEL_I420: i32 = 1;
const VIDEO_FRAME_TYPE_KEY: i32 = 3;
#[allow(dead_code)]
const VIDEO_FRAME_TYPE_DELTA: i32 = 4;

pub struct EncodedVideoPublisher {
    sender: *mut c_void,
    track: *mut c_void,
    conn: *mut c_void,
    width: i32,
    height: i32,
    fps_num: u32,
    fps_den: u32,
}

// SAFETY: the SDK handles are opaque C pointers that are not thread-local;
// we never alias them across threads without external synchronisation, and
// the callers in Task 11 keep the publishers in a single-threaded context.
unsafe impl Send for EncodedVideoPublisher {}

pub struct RawVideoPublisher {
    sender: *mut c_void,
    track: *mut c_void,
    conn: *mut c_void,
    width: i32,
    height: i32,
}

unsafe impl Send for RawVideoPublisher {}

pub(super) fn create_encoded(
    svc: *mut c_void,
    conn: *mut c_void,
    factory: *mut c_void,
) -> Result<EncodedVideoPublisher, AgoraError> {
    let sender = unsafe {
        sys::agora_media_node_factory_create_video_encoded_image_sender(factory)
    };
    if sender.is_null() {
        return Err(AgoraError::null(
            "agora_media_node_factory_create_video_encoded_image_sender",
        ));
    }
    let mut opts: sys::sender_options = unsafe { std::mem::zeroed() };
    opts.codec_type = VIDEO_CODEC_H264;
    opts.cc_mode = 0; // default CC mode
    let track = unsafe {
        sys::agora_service_create_custom_video_track_encoded(svc, sender, &mut opts as *mut _)
    };
    if track.is_null() {
        unsafe {
            sys::agora_video_encoded_image_sender_destroy(sender);
        }
        return Err(AgoraError::null(
            "agora_service_create_custom_video_track_encoded",
        ));
    }
    unsafe {
        sys::agora_local_video_track_set_enabled(track, 1);
    }
    Ok(EncodedVideoPublisher {
        sender,
        track,
        conn,
        width: 0,
        height: 0,
        fps_num: 30,
        fps_den: 1,
    })
}

pub(super) fn create_raw(
    svc: *mut c_void,
    conn: *mut c_void,
    factory: *mut c_void,
) -> Result<RawVideoPublisher, AgoraError> {
    let sender = unsafe {
        sys::agora_media_node_factory_create_video_frame_sender(factory)
    };
    if sender.is_null() {
        return Err(AgoraError::null(
            "agora_media_node_factory_create_video_frame_sender",
        ));
    }
    let track = unsafe { sys::agora_service_create_custom_video_track_frame(svc, sender) };
    if track.is_null() {
        unsafe {
            sys::agora_video_frame_sender_destroy(sender);
        }
        return Err(AgoraError::null(
            "agora_service_create_custom_video_track_frame",
        ));
    }
    unsafe {
        sys::agora_local_video_track_set_enabled(track, 1);
    }
    Ok(RawVideoPublisher {
        sender,
        track,
        conn,
        width: 0,
        height: 0,
    })
}

impl EncodedVideoPublisher {
    /// Set the picture dimensions and frame-rate ratio. Call once after
    /// the first H.264 AU has been seen and the source's width/height/fps
    /// are known (or pass values from `MediaInfo`).
    pub fn set_metadata(&mut self, width: u32, height: u32, fps_num: u32, fps_den: u32) {
        self.width = width as i32;
        self.height = height as i32;
        self.fps_num = fps_num;
        self.fps_den = fps_den.max(1);
    }

    /// Push one Annex-B-framed H.264 access-unit. `capture_time_ms` is a
    /// monotonic millisecond timestamp the SDK uses for ordering.
    pub fn push_h264(
        &self,
        au: &[u8],
        is_keyframe: bool,
        capture_time_ms: i64,
    ) -> Result<(), AgoraError> {
        let mut info: sys::encoded_video_frame_info = unsafe { std::mem::zeroed() };
        info.codec_type = VIDEO_CODEC_H264;
        info.width = self.width;
        info.height = self.height;
        info.frames_per_second = (self.fps_num as i32) / (self.fps_den as i32).max(1);
        info.frame_type = if is_keyframe {
            VIDEO_FRAME_TYPE_KEY
        } else {
            VIDEO_FRAME_TYPE_DELTA
        };
        info.rotation = 0;
        info.capture_time_ms = capture_time_ms;
        let rc = unsafe {
            sys::agora_video_encoded_image_sender_send(
                self.sender,
                au.as_ptr() as *const _,
                au.len() as u32,
                &info,
            )
        };
        check(rc, "agora_video_encoded_image_sender_send")
    }

    pub fn publish(&self) -> Result<(), AgoraError> {
        let local = unsafe { sys::agora_rtc_conn_get_local_user(self.conn) };
        let rc = unsafe { sys::agora_local_user_publish_video(local, self.track) };
        check(rc, "agora_local_user_publish_video")
    }

    pub fn unpublish(&self) -> Result<(), AgoraError> {
        let local = unsafe { sys::agora_rtc_conn_get_local_user(self.conn) };
        let rc = unsafe { sys::agora_local_user_unpublish_video(local, self.track) };
        check(rc, "agora_local_user_unpublish_video")
    }
}

impl Drop for EncodedVideoPublisher {
    fn drop(&mut self) {
        // TODO(phase3): publishers are moved into tokio::spawn'd pump tasks
        // in main.rs. If a pump task is still running when Session::drop runs
        // (e.g. --loop with SIGINT), Session destroys `conn` BEFORE the pump
        // task's tokio runtime is shut down → this Drop dereferences a freed
        // conn pointer. Benign in practice for the single-shot CLI because
        // the process exits seconds later, but is real UAF and blocks a
        // reusable Session. Fix: wire a tokio::CancellationToken that
        // Session::Drop fires + tokio::join the pump handles before the
        // SDK teardown runs.
        unsafe {
            let local = sys::agora_rtc_conn_get_local_user(self.conn);
            let _ = sys::agora_local_user_unpublish_video(local, self.track);
            sys::agora_local_video_track_destroy(self.track);
            sys::agora_video_encoded_image_sender_destroy(self.sender);
        }
    }
}

impl RawVideoPublisher {
    pub fn set_dimensions(&mut self, width: u32, height: u32) {
        self.width = width as i32;
        self.height = height as i32;
    }

    /// Push one yuv420p frame. `data` must be exactly width*height*3/2 bytes
    /// of planar Y+U+V; caller sizes it via `parse::yuv::frame_bytes`.
    pub fn push_yuv420p(&self, data: &[u8], pts_ms: i64) -> Result<(), AgoraError> {
        let mut frame: sys::external_video_frame = unsafe { std::mem::zeroed() };
        frame.type_ = VIDEO_BUFFER_RAW_DATA;
        frame.format = VIDEO_PIXEL_I420;
        frame.buffer = data.as_ptr() as *mut _;
        frame.stride = self.width;
        frame.height = self.height;
        frame.rotation = 0;
        frame.timestamp = pts_ms;
        let rc = unsafe { sys::agora_video_frame_sender_send(self.sender, &frame) };
        check(rc, "agora_video_frame_sender_send")
    }

    pub fn publish(&self) -> Result<(), AgoraError> {
        let local = unsafe { sys::agora_rtc_conn_get_local_user(self.conn) };
        let rc = unsafe { sys::agora_local_user_publish_video(local, self.track) };
        check(rc, "agora_local_user_publish_video")
    }

    pub fn unpublish(&self) -> Result<(), AgoraError> {
        let local = unsafe { sys::agora_rtc_conn_get_local_user(self.conn) };
        let rc = unsafe { sys::agora_local_user_unpublish_video(local, self.track) };
        check(rc, "agora_local_user_unpublish_video")
    }
}

impl Drop for RawVideoPublisher {
    fn drop(&mut self) {
        // TODO(phase3): same lifetime caveat as EncodedVideoPublisher::drop above.
        unsafe {
            let local = sys::agora_rtc_conn_get_local_user(self.conn);
            let _ = sys::agora_local_user_unpublish_video(local, self.track);
            sys::agora_local_video_track_destroy(self.track);
            sys::agora_video_frame_sender_destroy(self.sender);
        }
    }
}
